version: '3'

services:
  opensearch-cluster:
    image: ${OPENSEARCH_DOCKER_HUB_PROJECT:-opensearchproject}/opensearch:${OPENSEARCH_VERSION:-latest}${OPENSEARCH_DOCKER_REF}
    ports:
      - '9200:9200'
      - '9600:9600'
    environment:
      - 'OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD:-myStrongPassword123!}'
      - discovery.type=single-node
      - path.repo=/tmp/opensearch/repo
      - plugins.index_state_management.job_interval=1
