name: Proto Compatibility Comment

on:
  workflow_run:
    workflows:
      - Proto Compatibility Check
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download Proto Comment Payload
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: proto-comment-payload
          run-id: ${{ github.event.workflow_run.id }}

      - name: Parse Payload
        shell: bash -eo pipefail {0}
        run: |
          PR_NUMBER=$(jq -r '.pr_number' ./proto-comment-payload.json)
          REPORT=$(jq -r '.report' ./proto-comment-payload.json)

          vars=(
            PR_NUMBER
          )

          {
            for var in "${vars[@]}"
            do
              echo "${var}=${!var}"
            done
          } | tee "$GITHUB_ENV"

          # Save report for next step
          echo "$REPORT" > report.md

      - name: Find Existing Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-author: github-actions[bot]
          body-includes: Proto Compatibility Report

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ env.PR_NUMBER }}
          body: |
            ## Proto Compatibility Report

            $(cat report.md)

            ---
            *Generated by Proto Compatibility Check*
          edit-mode: replace
