name: Trigger Proto Convert

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Proto Convert Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_OSPT_PAT }}
          repository: lucy66hw/opensearch-protobufs
          event-type: spec-updated
          client-payload: |
            {
              "spec_repository": "lucy66hw/opensearch-api-specification",
              "spec_tag": "main-latest",
              "pr_number": "${{ github.event.pull_request.number || '' }}",
              "ref": "${{ github.ref }}"
            }